# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcpap_wut.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.upload_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upload_lineEdit.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.upload_lineEdit.setText("")
        self.upload_lineEdit.setPlaceholderText("")
        self.upload_lineEdit.setObjectName("upload_lineEdit")
        self.upload_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.upload_pushButton.setGeometry(QtCore.QRect(250, 20, 31, 21))
        self.upload_pushButton.setObjectName("upload_pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 221, 371))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.window_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.window_lineEdit.setObjectName("window_lineEdit")
        self.gridLayout.addWidget(self.window_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tx_power_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tx_power_lineEdit.setObjectName("tx_power_lineEdit")
        self.gridLayout.addWidget(self.tx_power_lineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tx_gain_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tx_gain_lineEdit.setObjectName("tx_gain_lineEdit")
        self.gridLayout.addWidget(self.tx_gain_lineEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.rx_gain_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.rx_gain_lineEdit.setObjectName("rx_gain_lineEdit")
        self.gridLayout.addWidget(self.rx_gain_lineEdit, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.tx_heigh_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tx_heigh_lineEdit.setObjectName("tx_heigh_lineEdit")
        self.gridLayout.addWidget(self.tx_heigh_lineEdit, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.rx_heigh_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.rx_heigh_lineEdit.setObjectName("rx_heigh_lineEdit")
        self.gridLayout.addWidget(self.rx_heigh_lineEdit, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.fc_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.fc_lineEdit.setObjectName("fc_lineEdit")
        self.gridLayout.addWidget(self.fc_lineEdit, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.cable_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.cable_lineEdit.setObjectName("cable_lineEdit")
        self.gridLayout.addWidget(self.cable_lineEdit, 7, 1, 1, 1)
        self.confirm_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.gridLayout.addWidget(self.confirm_pushButton, 8, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 60, 191, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.delay_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.delay_pushButton.setObjectName("delay_pushButton")
        self.verticalLayout.addWidget(self.delay_pushButton)
        self.frequency_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.frequency_pushButton.setObjectName("frequency_pushButton")
        self.verticalLayout.addWidget(self.frequency_pushButton)
        self.power_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.power_pushButton.setObjectName("power_pushButton")
        self.verticalLayout.addWidget(self.power_pushButton)
        self.angel_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.angel_pushButton.setObjectName("angel_pushButton")
        self.verticalLayout.addWidget(self.angel_pushButton)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 270, 191, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.image_1_label = QtWidgets.QLabel(self.centralwidget)
        self.image_1_label.setGeometry(QtCore.QRect(460, 10, 341, 221))
        self.image_1_label.setText("")
        self.image_1_label.setObjectName("image_1_label")
        self.image_2_label = QtWidgets.QLabel(self.centralwidget)
        self.image_2_label.setGeometry(QtCore.QRect(460, 250, 341, 221))
        self.image_2_label.setText("")
        self.image_2_label.setObjectName("image_2_label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 480, 351, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.groupBox_2)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.horizontalHeader().setDefaultSectionSize(82)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setDefaultSectionSize(32)
        self.tableView.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)
        self.icon_label = QtWidgets.QLabel(self.centralwidget)
        self.icon_label.setGeometry(QtCore.QRect(10, 470, 151, 101))
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuVieew = QtWidgets.QMenu(self.menubar)
        self.menuVieew.setObjectName("menuVieew")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuVieew.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upload_pushButton.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Window:"))
        self.label_2.setText(_translate("MainWindow", "Tx Power:"))
        self.label_3.setText(_translate("MainWindow", "Tx Gain:"))
        self.label_4.setText(_translate("MainWindow", "Rx Gain:"))
        self.label_9.setText(_translate("MainWindow", "Tx Heigh:"))
        self.label_10.setText(_translate("MainWindow", "Rx Heigh:"))
        self.label_11.setText(_translate("MainWindow", "fc:"))
        self.label_12.setText(_translate("MainWindow", "Cable:"))
        self.confirm_pushButton.setText(_translate("MainWindow", "Confirm"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Functions"))
        self.delay_pushButton.setText(_translate("MainWindow", "Delay Domain"))
        self.frequency_pushButton.setText(_translate("MainWindow", "Frequency Domain"))
        self.power_pushButton.setText(_translate("MainWindow", "Power Domain"))
        self.angel_pushButton.setText(_translate("MainWindow", "Angel Domain"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Other Functions"))
        self.pushButton.setText(_translate("MainWindow", "A"))
        self.pushButton_3.setText(_translate("MainWindow", "B"))
        self.pushButton_2.setText(_translate("MainWindow", "C"))
        self.pushButton_4.setText(_translate("MainWindow", "D"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Results"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTool.setTitle(_translate("MainWindow", "Edit"))
        self.menuVieew.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

