# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcpap_wut.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.upload_txt_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upload_txt_lineEdit.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.upload_txt_lineEdit.setText("")
        self.upload_txt_lineEdit.setPlaceholderText("")
        self.upload_txt_lineEdit.setObjectName("upload_txt_lineEdit")
        self.upload_txt_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.upload_txt_pushButton.setGeometry(QtCore.QRect(250, 20, 31, 21))
        self.upload_txt_pushButton.setObjectName("upload_txt_pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 271, 341))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.window_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.window_lineEdit.setObjectName("window_lineEdit")
        self.gridLayout.addWidget(self.window_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tx_power_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tx_power_lineEdit.setObjectName("tx_power_lineEdit")
        self.gridLayout.addWidget(self.tx_power_lineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tx_gain_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tx_gain_lineEdit.setObjectName("tx_gain_lineEdit")
        self.gridLayout.addWidget(self.tx_gain_lineEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.rx_gain_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.rx_gain_lineEdit.setObjectName("rx_gain_lineEdit")
        self.gridLayout.addWidget(self.rx_gain_lineEdit, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.tx_heigh_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tx_heigh_lineEdit.setObjectName("tx_heigh_lineEdit")
        self.gridLayout.addWidget(self.tx_heigh_lineEdit, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.rx_heigh_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.rx_heigh_lineEdit.setObjectName("rx_heigh_lineEdit")
        self.gridLayout.addWidget(self.rx_heigh_lineEdit, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.fc_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.fc_lineEdit.setObjectName("fc_lineEdit")
        self.gridLayout.addWidget(self.fc_lineEdit, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.att_mark_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.att_mark_lineEdit.setObjectName("att_mark_lineEdit")
        self.gridLayout.addWidget(self.att_mark_lineEdit, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.cable_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.cable_lineEdit.setObjectName("cable_lineEdit")
        self.gridLayout.addWidget(self.cable_lineEdit, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.chirp_num_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.chirp_num_lineEdit.setObjectName("chirp_num_lineEdit")
        self.gridLayout.addWidget(self.chirp_num_lineEdit, 9, 1, 1, 1)
        self.confirm_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.gridLayout.addWidget(self.confirm_pushButton, 10, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 440, 271, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.power_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.power_pushButton.setObjectName("power_pushButton")
        self.gridLayout_3.addWidget(self.power_pushButton, 1, 0, 1, 1)
        self.delay_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.delay_pushButton.setObjectName("delay_pushButton")
        self.gridLayout_3.addWidget(self.delay_pushButton, 0, 0, 1, 1)
        self.frequency_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.frequency_pushButton.setObjectName("frequency_pushButton")
        self.gridLayout_3.addWidget(self.frequency_pushButton, 0, 1, 1, 1)
        self.angel_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.angel_pushButton.setObjectName("angel_pushButton")
        self.gridLayout_3.addWidget(self.angel_pushButton, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 530, 271, 84))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.import_params_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.import_params_pushButton.setFont(font)
        self.import_params_pushButton.setObjectName("import_params_pushButton")
        self.gridLayout_4.addWidget(self.import_params_pushButton, 0, 0, 1, 1)
        self.B_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.B_pushButton.setObjectName("B_pushButton")
        self.gridLayout_4.addWidget(self.B_pushButton, 0, 1, 1, 1)
        self.C_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.C_pushButton.setObjectName("C_pushButton")
        self.gridLayout_4.addWidget(self.C_pushButton, 1, 0, 1, 1)
        self.D_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.D_pushButton.setObjectName("D_pushButton")
        self.gridLayout_4.addWidget(self.D_pushButton, 1, 1, 1, 1)
        self.upload_excel_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.upload_excel_lineEdit.setGeometry(QtCore.QRect(10, 50, 221, 21))
        self.upload_excel_lineEdit.setText("")
        self.upload_excel_lineEdit.setPlaceholderText("")
        self.upload_excel_lineEdit.setObjectName("upload_excel_lineEdit")
        self.upload_excel_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.upload_excel_pushButton.setGeometry(QtCore.QRect(250, 50, 31, 21))
        self.upload_excel_pushButton.setObjectName("upload_excel_pushButton")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(970, 18, 171, 581))
        self.toolBox.setObjectName("toolBox")
        self.main_doppler = QtWidgets.QWidget()
        self.main_doppler.setGeometry(QtCore.QRect(0, 0, 171, 477))
        self.main_doppler.setObjectName("main_doppler")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_doppler)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_doppler_tableWidget = QtWidgets.QTableWidget(self.main_doppler)
        self.main_doppler_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.main_doppler_tableWidget.setObjectName("main_doppler_tableWidget")
        self.main_doppler_tableWidget.setColumnCount(0)
        self.main_doppler_tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.main_doppler_tableWidget)
        self.toolBox.addItem(self.main_doppler, "")
        self.delay_domain = QtWidgets.QWidget()
        self.delay_domain.setGeometry(QtCore.QRect(0, 0, 171, 477))
        self.delay_domain.setObjectName("delay_domain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.delay_domain)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.delay_domain_tableWidget = QtWidgets.QTableWidget(self.delay_domain)
        self.delay_domain_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.delay_domain_tableWidget.setObjectName("delay_domain_tableWidget")
        self.delay_domain_tableWidget.setColumnCount(0)
        self.delay_domain_tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.delay_domain_tableWidget)
        self.toolBox.addItem(self.delay_domain, "")
        self.frequency_domain = QtWidgets.QWidget()
        self.frequency_domain.setGeometry(QtCore.QRect(0, 0, 171, 477))
        self.frequency_domain.setObjectName("frequency_domain")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frequency_domain)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frequency_domain_tableWidget = QtWidgets.QTableWidget(self.frequency_domain)
        self.frequency_domain_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.frequency_domain_tableWidget.setObjectName("frequency_domain_tableWidget")
        self.frequency_domain_tableWidget.setColumnCount(0)
        self.frequency_domain_tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.frequency_domain_tableWidget)
        self.toolBox.addItem(self.frequency_domain, "")
        self.power_domain = QtWidgets.QWidget()
        self.power_domain.setGeometry(QtCore.QRect(0, 0, 171, 477))
        self.power_domain.setObjectName("power_domain")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.power_domain)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.power_domain_tableWidget = QtWidgets.QTableWidget(self.power_domain)
        self.power_domain_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.power_domain_tableWidget.setObjectName("power_domain_tableWidget")
        self.power_domain_tableWidget.setColumnCount(0)
        self.power_domain_tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.power_domain_tableWidget)
        self.toolBox.addItem(self.power_domain, "")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 0, 670, 530))
        self.groupBox_2.setObjectName("groupBox_2")
        self.img_label = QtWidgets.QLabel(self.groupBox_2)
        self.img_label.setGeometry(QtCore.QRect(15, 30, 640, 480))
        self.img_label.setText("")
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.details_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.details_pushButton.setGeometry(QtCore.QRect(580, 490, 75, 23))
        self.details_pushButton.setObjectName("details_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1160, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuVieew = QtWidgets.QMenu(self.menubar)
        self.menuVieew.setObjectName("menuVieew")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuVieew.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RCPAP"))
        self.upload_txt_pushButton.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Window:"))
        self.window_lineEdit.setText(_translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "Tx Power:"))
        self.tx_power_lineEdit.setText(_translate("MainWindow", "16"))
        self.label_3.setText(_translate("MainWindow", "Tx Gain:"))
        self.tx_gain_lineEdit.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "Rx Gain:"))
        self.rx_gain_lineEdit.setText(_translate("MainWindow", "10"))
        self.label_9.setText(_translate("MainWindow", "Tx Heigh:"))
        self.tx_heigh_lineEdit.setText(_translate("MainWindow", "1.57"))
        self.label_10.setText(_translate("MainWindow", "Rx Heigh:"))
        self.rx_heigh_lineEdit.setText(_translate("MainWindow", "1.78"))
        self.label_11.setText(_translate("MainWindow", "fc:"))
        self.fc_lineEdit.setText(_translate("MainWindow", "5.9e9"))
        self.label_13.setText(_translate("MainWindow", "ATT Mark:"))
        self.att_mark_lineEdit.setText(_translate("MainWindow", "23"))
        self.label_12.setText(_translate("MainWindow", "Cable:"))
        self.cable_lineEdit.setText(_translate("MainWindow", "6"))
        self.label_14.setText(_translate("MainWindow", "Chirp Num:"))
        self.chirp_num_lineEdit.setText(_translate("MainWindow", "(1933+1933+1934)/3"))
        self.confirm_pushButton.setText(_translate("MainWindow", "Confirm"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Functions"))
        self.power_pushButton.setText(_translate("MainWindow", "Power Domain"))
        self.delay_pushButton.setText(_translate("MainWindow", "Delay Domain"))
        self.frequency_pushButton.setText(_translate("MainWindow", "Frequency Domain"))
        self.angel_pushButton.setText(_translate("MainWindow", "Angel Domain"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Other Functions"))
        self.import_params_pushButton.setText(_translate("MainWindow", "Import the latest params"))
        self.B_pushButton.setText(_translate("MainWindow", "B"))
        self.C_pushButton.setText(_translate("MainWindow", "C"))
        self.D_pushButton.setText(_translate("MainWindow", "D"))
        self.upload_excel_pushButton.setText(_translate("MainWindow", "..."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.main_doppler), _translate("MainWindow", "Main Doppler"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.delay_domain), _translate("MainWindow", "Delay Domain"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.frequency_domain), _translate("MainWindow", "Frequency Domain"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.power_domain), _translate("MainWindow", "Power Domain"))
        self.groupBox_2.setTitle(_translate("MainWindow", "View"))
        self.details_pushButton.setText(_translate("MainWindow", "Details..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTool.setTitle(_translate("MainWindow", "Edit"))
        self.menuVieew.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

